### ISSUE TITLE
[2014-01-14] Link to NFEs is broken

### ISSUE THREAD

**Issue by brianloveswords** [kangax/perfectionkills.com#1]
In this paragraph in the [2014-01-14 article](https://github.com/kangax/perfectionkills.com/blob/gh-pages/_posts/2014-01-14-state-of-function-decompilation-in-javascript.md):

> Back in the days, things were really bad. Safari <=2.x, for example, didn't even conform to valid Function Declaration syntax. It would go wild with things like "(Internal Function)" or "[function]" or drop identifiers from NFE's, just because.

I would submit a PR but I don't know where the link should go!

**Comment by kangax** [comment]
Fixed
